# Site settings
description: ALL CRASHING THINGS IN MODERATION ..... My thoughts on web technology, business and days politics
baseurl: "http://www.kimmohintikka.com/" # the subpath of your site, e.g. /blog/
url: "http://www.kimmohintikka.com/" # the base hostname & protocol for your site

# User settings
username: Kimmo Hintikka
user_description: Kimmo Hintikka Web practitioner. Unapologetic communicator. Professional introvert.
user_title: ALL CRASHING THINGS IN MODERATION....
email: hintikkakimmo@gmail.com
twitter_username: KimmoHintikka
github_username: HintikkaKimmo
linkedin_username: kimmohintikka
disqus_username: kimmohintikka

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
