# Site settings
description: A blog about lorem ipsum dolor sit amet
baseurl: "http://www.kimmohintikka.com/" # the subpath of your site, e.g. /blog/
url: "http://www.kimmohintikka.com/" # the base hostname & protocol for your site

# User settings
username: Lorem Ipsum
user_description: Anon Developer at Lorem Ipsum Dolor
user_title: Kimmo Hintikka
email: hintikkakimmo@gmail.com
twitter_username: KimmoHintikka
github_username:  HintikkaKimmo
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
